"""postgresql release baseline

Revision ID: 20260711_0001
Revises:
Create Date: 2026-07-11 09:17:46.502677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20260711_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_workspaces",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_workspaces_id"), "project_workspaces", ["id"], unique=False)
    op.create_index(
        op.f("ix_project_workspaces_project_id"), "project_workspaces", ["project_id"], unique=True
    )
    op.create_table(
        "tasks",
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "task_type",
            sa.Enum(
                "VIDEO_GENERATION",
                "IMAGE_GENERATION",
                "SCRIPT_WRITING",
                "VIDEO_EDITING",
                "CONCEPT_PLANNING",
                name="tasktype",
            ),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.String(length=100), nullable=True),
        sa.Column("session_id", sa.String(length=100), nullable=True),
        sa.Column("input_parameters", sa.JSON(), nullable=True),
        sa.Column("output_metadata", sa.JSON(), nullable=True),
        sa.Column("progress_percentage", sa.Integer(), nullable=True),
        sa.Column("current_step", sa.String(length=100), nullable=True),
        sa.Column("total_steps", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("max_retries", sa.Integer(), nullable=True),
        sa.Column("estimated_duration", sa.Integer(), nullable=True),
        sa.Column("actual_duration", sa.Integer(), nullable=True),
        sa.Column("resource_usage", sa.JSON(), nullable=True),
        sa.Column("quality_score", sa.Integer(), nullable=True),
        sa.Column("quality_feedback", sa.Text(), nullable=True),
        sa.Column("requires_human_review", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
    op.create_index(op.f("ix_tasks_task_id"), "tasks", ["task_id"], unique=True)
    op.create_table(
        "scenes",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("scene_number", sa.Integer(), nullable=False),
        sa.Column(
            "scene_type",
            sa.Enum("INTRO", "MAIN_CONTENT", "TRANSITION", "OUTRO", "BACKGROUND", name="scenetype"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("script_text", sa.Text(), nullable=True),
        sa.Column("narrative_description", sa.Text(), nullable=True),
        sa.Column("visual_description", sa.Text(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("start_time", sa.Float(), nullable=True),
        sa.Column("end_time", sa.Float(), nullable=True),
        sa.Column("background_prompt", sa.Text(), nullable=True),
        sa.Column("character_descriptions", sa.JSON(), nullable=True),
        sa.Column("props_and_objects", sa.JSON(), nullable=True),
        sa.Column("mood_and_atmosphere", sa.String(length=100), nullable=True),
        sa.Column("voice_over_text", sa.Text(), nullable=True),
        sa.Column("background_music_style", sa.String(length=100), nullable=True),
        sa.Column("sound_effects", sa.JSON(), nullable=True),
        sa.Column("camera_angle", sa.String(length=50), nullable=True),
        sa.Column("camera_movement", sa.String(length=50), nullable=True),
        sa.Column("lighting_style", sa.String(length=50), nullable=True),
        sa.Column("art_style", sa.String(length=100), nullable=True),
        sa.Column("color_palette", sa.JSON(), nullable=True),
        sa.Column("visual_effects", sa.JSON(), nullable=True),
        sa.Column("generation_parameters", sa.JSON(), nullable=True),
        sa.Column("quality_metrics", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scenes_id"), "scenes", ["id"], unique=False)
    op.create_table(
        "workflow_sessions",
        sa.Column("task_db_id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=50), nullable=False),
        sa.Column("project_id", sa.String(length=100), nullable=True),
        sa.Column("episode_id", sa.String(length=100), nullable=True),
        sa.Column("shared_memory_id", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("current_node_key", sa.String(length=100), nullable=True),
        sa.Column("current_attempt_id", sa.Integer(), nullable=True),
        sa.Column("input_payload", sa.JSON(), nullable=True),
        sa.Column("gate_policy", sa.JSON(), nullable=True),
        sa.Column("summary_output", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["task_db_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_sessions_episode_id"), "workflow_sessions", ["episode_id"], unique=False
    )
    op.create_index(op.f("ix_workflow_sessions_id"), "workflow_sessions", ["id"], unique=False)
    op.create_index(
        op.f("ix_workflow_sessions_project_id"), "workflow_sessions", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_sessions_shared_memory_id"),
        "workflow_sessions",
        ["shared_memory_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_sessions_task_db_id"), "workflow_sessions", ["task_db_id"], unique=False
    )
    op.create_table(
        "resources",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("scene_id", sa.Integer(), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_url", sa.String(length=500), nullable=True),
        sa.Column(
            "resource_type",
            sa.Enum(
                "IMAGE",
                "VIDEO",
                "AUDIO",
                "VOICE_OVER",
                "TEXT",
                "SCRIPT",
                "THUMBNAIL",
                "TEMP_FILE",
                name="resourcetype",
            ),
            nullable=False,
        ),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("frame_rate", sa.Integer(), nullable=True),
        sa.Column("bit_rate", sa.Integer(), nullable=True),
        sa.Column("generation_parameters", sa.JSON(), nullable=True),
        sa.Column("generation_model", sa.String(length=100), nullable=True),
        sa.Column("generation_prompt", sa.Text(), nullable=True),
        sa.Column("generation_seed", sa.Integer(), nullable=True),
        sa.Column("quality_score", sa.Integer(), nullable=True),
        sa.Column("processing_status", sa.String(length=50), nullable=True),
        sa.Column("processing_metadata", sa.JSON(), nullable=True),
        sa.Column("storage_provider", sa.String(length=50), nullable=True),
        sa.Column("access_permissions", sa.String(length=50), nullable=True),
        sa.Column("expiry_date", sa.Integer(), nullable=True),
        sa.Column("download_count", sa.Integer(), nullable=True),
        sa.Column("last_accessed", sa.Integer(), nullable=True),
        sa.Column("is_temporary", sa.Boolean(), nullable=True),
        sa.Column("is_generated", sa.Boolean(), nullable=True),
        sa.Column("is_final_output", sa.Boolean(), nullable=True),
        sa.Column("parent_resource_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_resource_id"],
            ["resources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scenes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_resources_id"), "resources", ["id"], unique=False)
    op.create_table(
        "workflow_node_states",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("node_key", sa.String(length=100), nullable=False),
        sa.Column("node_type", sa.String(length=50), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("scope_type", sa.String(length=30), nullable=False),
        sa.Column("scope_ref", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("revision_index", sa.Integer(), nullable=False),
        sa.Column("gate_required", sa.Boolean(), nullable=False),
        sa.Column("last_gate_id", sa.Integer(), nullable=True),
        sa.Column("artifact_refs", sa.JSON(), nullable=True),
        sa.Column("diagnostics", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["workflow_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_node_states_id"), "workflow_node_states", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_node_states_node_key"), "workflow_node_states", ["node_key"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_node_states_session_id"),
        "workflow_node_states",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "workflow_node_attempts",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("trigger_reason", sa.String(length=30), nullable=False),
        sa.Column("requested_by", sa.String(length=30), nullable=False),
        sa.Column("input_contract", sa.JSON(), nullable=True),
        sa.Column("continuation_checkpoint", sa.JSON(), nullable=True),
        sa.Column("output_artifacts", sa.JSON(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("lease_token", sa.String(length=64), nullable=True),
        sa.Column("lease_owner", sa.String(length=100), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["workflow_node_states.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["workflow_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_node_attempts_id"), "workflow_node_attempts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_node_attempts_node_id"),
        "workflow_node_attempts",
        ["node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_node_attempts_session_id"),
        "workflow_node_attempts",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "workflow_gates",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=True),
        sa.Column("gate_name", sa.String(length=50), nullable=False),
        sa.Column("gate_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("contract_version", sa.String(length=20), nullable=False),
        sa.Column("scope", sa.JSON(), nullable=True),
        sa.Column("artifact_refs", sa.JSON(), nullable=True),
        sa.Column("facts", sa.JSON(), nullable=True),
        sa.Column("result_code", sa.String(length=30), nullable=True),
        sa.Column("reason_code", sa.String(length=100), nullable=True),
        sa.Column("diagnostics", sa.JSON(), nullable=True),
        sa.Column("allowed_actions", sa.JSON(), nullable=True),
        sa.Column("recommended_action", sa.String(length=30), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["workflow_node_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["workflow_node_states.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["workflow_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_gates_attempt_id"), "workflow_gates", ["attempt_id"], unique=False
    )
    op.create_index(op.f("ix_workflow_gates_id"), "workflow_gates", ["id"], unique=False)
    op.create_index(op.f("ix_workflow_gates_node_id"), "workflow_gates", ["node_id"], unique=False)
    op.create_index(
        op.f("ix_workflow_gates_session_id"), "workflow_gates", ["session_id"], unique=False
    )
    op.create_table(
        "workflow_published_deliverables",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("deliverable_type", sa.String(length=50), nullable=False),
        sa.Column("scope_type", sa.String(length=30), nullable=False),
        sa.Column("scope_id", sa.String(length=100), nullable=True),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("payload_ref", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=True),
        sa.Column("is_candidate", sa.Boolean(), nullable=False),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["workflow_node_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["workflow_node_states.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["workflow_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_published_deliverables_attempt_id"),
        "workflow_published_deliverables",
        ["attempt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_published_deliverables_deliverable_type"),
        "workflow_published_deliverables",
        ["deliverable_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_published_deliverables_id"),
        "workflow_published_deliverables",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_published_deliverables_node_id"),
        "workflow_published_deliverables",
        ["node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_published_deliverables_session_id"),
        "workflow_published_deliverables",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "workflow_gate_decisions",
        sa.Column("gate_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("actor_type", sa.String(length=30), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=True),
        sa.Column("feedback_text", sa.Text(), nullable=True),
        sa.Column("structured_constraints", sa.JSON(), nullable=True),
        sa.Column("invalidation_scope", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gate_id"],
            ["workflow_gates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["workflow_node_states.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["workflow_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_gate_decisions_gate_id"),
        "workflow_gate_decisions",
        ["gate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_gate_decisions_id"), "workflow_gate_decisions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_gate_decisions_node_id"),
        "workflow_gate_decisions",
        ["node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_gate_decisions_session_id"),
        "workflow_gate_decisions",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workflow_gate_decisions_session_id"), table_name="workflow_gate_decisions"
    )
    op.drop_index(op.f("ix_workflow_gate_decisions_node_id"), table_name="workflow_gate_decisions")
    op.drop_index(op.f("ix_workflow_gate_decisions_id"), table_name="workflow_gate_decisions")
    op.drop_index(op.f("ix_workflow_gate_decisions_gate_id"), table_name="workflow_gate_decisions")
    op.drop_table("workflow_gate_decisions")
    op.drop_index(
        op.f("ix_workflow_published_deliverables_session_id"),
        table_name="workflow_published_deliverables",
    )
    op.drop_index(
        op.f("ix_workflow_published_deliverables_node_id"),
        table_name="workflow_published_deliverables",
    )
    op.drop_index(
        op.f("ix_workflow_published_deliverables_id"), table_name="workflow_published_deliverables"
    )
    op.drop_index(
        op.f("ix_workflow_published_deliverables_deliverable_type"),
        table_name="workflow_published_deliverables",
    )
    op.drop_index(
        op.f("ix_workflow_published_deliverables_attempt_id"),
        table_name="workflow_published_deliverables",
    )
    op.drop_table("workflow_published_deliverables")
    op.drop_index(op.f("ix_workflow_gates_session_id"), table_name="workflow_gates")
    op.drop_index(op.f("ix_workflow_gates_node_id"), table_name="workflow_gates")
    op.drop_index(op.f("ix_workflow_gates_id"), table_name="workflow_gates")
    op.drop_index(op.f("ix_workflow_gates_attempt_id"), table_name="workflow_gates")
    op.drop_table("workflow_gates")
    op.drop_index(op.f("ix_workflow_node_attempts_session_id"), table_name="workflow_node_attempts")
    op.drop_index(op.f("ix_workflow_node_attempts_node_id"), table_name="workflow_node_attempts")
    op.drop_index(op.f("ix_workflow_node_attempts_id"), table_name="workflow_node_attempts")
    op.drop_table("workflow_node_attempts")
    op.drop_index(op.f("ix_workflow_node_states_session_id"), table_name="workflow_node_states")
    op.drop_index(op.f("ix_workflow_node_states_node_key"), table_name="workflow_node_states")
    op.drop_index(op.f("ix_workflow_node_states_id"), table_name="workflow_node_states")
    op.drop_table("workflow_node_states")
    op.drop_index(op.f("ix_resources_id"), table_name="resources")
    op.drop_table("resources")
    op.drop_index(op.f("ix_workflow_sessions_task_db_id"), table_name="workflow_sessions")
    op.drop_index(op.f("ix_workflow_sessions_shared_memory_id"), table_name="workflow_sessions")
    op.drop_index(op.f("ix_workflow_sessions_project_id"), table_name="workflow_sessions")
    op.drop_index(op.f("ix_workflow_sessions_id"), table_name="workflow_sessions")
    op.drop_index(op.f("ix_workflow_sessions_episode_id"), table_name="workflow_sessions")
    op.drop_table("workflow_sessions")
    op.drop_index(op.f("ix_scenes_id"), table_name="scenes")
    op.drop_table("scenes")
    op.drop_index(op.f("ix_tasks_task_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_project_workspaces_project_id"), table_name="project_workspaces")
    op.drop_index(op.f("ix_project_workspaces_id"), table_name="project_workspaces")
    op.drop_table("project_workspaces")
    # ### end Alembic commands ###
